### ISSUE TITLE
Trac to GitHub user mapping

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted-trac-migration#2]
Use this ticket to report any issue in the Trac to GitHub happing

**Comment by adiroiban** [comment]
My list so far
* thijs
* itamar ->  itamarst
* lvh
* tom.prince
* multani

**Comment by danuker** [comment]
Maybe a table is the same. Multiple Trac nicks can get the same GitHub nick.

I wouldn't like to match GitHub accounts automatically. For example, thijs on Trac is not thijs on GitHub.

|Trac|GitHub|
|----|--------|
|thijs|thijstriemstra|
|itamar|itamarst|
|tom.prince|tomprince|

**Comment by danuker** [comment]
@adiroiban if the users are in the table above, and have the same GitHub ID as Trac ID, then no need to mention them

**Comment by danuker** [comment]
The users added to the left column by me so far will be included in the `twisted/twisted-trac-migration` starting #6971 . For the `twisted/twisted` run I will include the top 100 accounts by ticket changes on Trac, as well as all members of https://github.com/orgs/twisted/teams .

**Comment by danuker** [comment]
This is done.

**Comment by danuker** [comment]
Looks like I can't edit #1 anymore; might be because I was editing it while closing this. will try to reopen this

**Comment by danuker** [comment]
Still won't work.
